[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
data = { path = "../../crates/data" }
plot = { path = "../../crates/plot" }
app-core = { path = "../../crates/app-core" }
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.10"
log = "0.4" 